/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathRouteImport } from './routes/path'
import { Route as PlaceRouteImport } from './routes/place'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as PracticeModeRouteImport } from './routes/practice/$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceRoute = PlaceRouteImport.update({
  id: '/place',
  path: '/place',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeModeRoute = PracticeModeRouteImport.update({
  id: '/practice/$mode',
  path: '/practice/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/path': typeof PathRoute
  '/place': typeof PlaceRoute
  '/progress': typeof ProgressRoute
  '/tutor': typeof TutorRoute
  '/lesson/$id': typeof LessonIdRoute
  '/practice/$mode': typeof PracticeModeRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/path': typeof PathRoute
  '/place': typeof PlaceRoute
  '/progress': typeof ProgressRoute
  '/tutor': typeof TutorRoute
  '/lesson/$id': typeof LessonIdRoute
  '/practice/$mode': typeof PracticeModeRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/path': typeof PathRoute
  '/place': typeof PlaceRoute
  '/progress': typeof ProgressRoute
  '/tutor': typeof TutorRoute
  '/lesson/$id': typeof LessonIdRoute
  '/practice/$mode': typeof PracticeModeRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/path'
    | '/place'
    | '/progress'
    | '/tutor'
    | '/lesson/$id'
    | '/practice/$mode'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/path'
    | '/place'
    | '/progress'
    | '/tutor'
    | '/lesson/$id'
    | '/practice/$mode'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/path'
    | '/place'
    | '/progress'
    | '/tutor'
    | '/lesson/$id'
    | '/practice/$mode'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathRoute: typeof PathRoute
  PlaceRoute: typeof PlaceRoute
  ProgressRoute: typeof ProgressRoute
  TutorRoute: typeof TutorRoute
  LessonIdRoute: typeof LessonIdRoute
  PracticeModeRoute: typeof PracticeModeRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place': {
      id: '/place'
      path: '/place'
      fullPath: '/place'
      preLoaderRoute: typeof PlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$mode': {
      id: '/practice/$mode'
      path: '/practice/$mode'
      fullPath: '/practice/$mode'
      preLoaderRoute: typeof PracticeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathRoute: PathRoute,
  PlaceRoute: PlaceRoute,
  ProgressRoute: ProgressRoute,
  TutorRoute: TutorRoute,
  LessonIdRoute: LessonIdRoute,
  PracticeModeRoute: PracticeModeRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
